### ISSUE TITLE
Domain regex is too aggressive

### ISSUE THREAD

**Issue by polm** [lucahammer/fedifinder#129]
Thanks for making this tool.

While using it, I noticed my account wasn't picked up. I thought this was an issue with my username being purely numeric, but it looks like the check for false-positive domains is overzealous, and any domain that contains the string `t.co` will be ignored. So my handle is `https://fedi.dampfkraft.com/@23`, and the `dampfkraf[t.co]m` part triggers the ignore regex. 

I think you might have to do that check after parsing the URL into its parts.

**Comment by lucahammer** [comment]
Should be fixed by #127, but I need to make some changes before I can re-deploy.

**Comment by polm** [comment]
Oh, glad it's fixed! Sorry I missed the PR.
