### ISSUE TITLE
Adding any list to scan adds the first list name to the "Already scanned" section.

### ISSUE THREAD

**Issue by rbairwell** [lucahammer/fedifinder#167]
Using the new/current version on https://fedifinder.glitch.me/, I scanned my Twitter followers (annoyingly it limited it to 1,000 of the 1,194 accounts I follow), and then went to scan the lists. As I was adding each of the 21 lists, I noticed they all showed (at the top of the "Scan your network" section) the same list name (that of the first list) - although the user counts were correct and the select list correctly removed the selected item.

Browser: Brave [Version 1.45.131 Chromium: 107.0.5304.110 (Official Build) (64-bit)
OS: Windows 10 Pro

**Comment by lucahammer** [comment]
Thanks for bringing this to my attention. The list names should be fixed now. Let me know if you still have that issue.

Regarding the number of scanned accounts: They are scanned in batches of 1000. And each batch is displayed in the list of scanned accounts. You should see "1000 followers, 194 followers". Each batch takes a few seconds.

**Comment by rbairwell** [comment]
Thanks - for some reason my brain didn't register the "1,000 followings, 195 followings" as two batches of the same scan (I was expecting "1,195" to appear somewhere).

Thank you again for a wonderful service!
