### ISSUE TITLE
Not picking up own handle in Twitter profile in URL field

### ISSUE THREAD

**Issue by cr08** [lucahammer/fedifinder#172]
Not sure if maybe I'm doing something dumb or if something with the tld may be interfering.

Twitter profile: @Vchat20
Mastodon handle: https://neurodifferent.me/@Vchat20

I've got this entered in the URL field in my profile but under step 2 Fedifinder consistently says no handles were found.

**Comment by lucahammer** [comment]
The filter to remove telegram urls was too aggressive. Fixed with the new version.
