### ISSUE TITLE
upon completion fedifinder shows blank white page

### ISSUE THREAD

**Issue by BugDave** [lucahammer/fedifinder#178]
everything seems to be ok but then it shows a white screen. log shows an "undefined is not an object" error. happens in safari, FF, Edge, and Vivaldi 

<img width="1573" alt="error" src="https://user-images.githubusercontent.com/400755/207475712-64ed372d-53b1-4fdd-a1a3-955404f3d647.png">

**Comment by nepeat** [comment]
Looks like it may be related to #175 if it is showing the `data.handles.length` and if you are seeing this error.

`Proxy {error: 'not a handle or not a domain'} client.js:245`


If you are seeing that, PR #176 has been cut to fix that.

**Comment by lucahammer** [comment]
@BugDave The PR from @nepeat was merged. Do you still get the error?

**Comment by lucahammer** [comment]
I pushed another fix. If you have the time, it would be great of you could give it another try. Thanks.
