### ISSUE TITLE
fedifinder.glitch.me is no longer working 

### ISSUE THREAD

**Issue by ltsc1980** [lucahammer/fedifinder#210]
```
Error: Error: Request failed with code 401
    at /app/server.js:89:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

EDIT: It's fedifinder.glitch.me that I receive error messages. v1 and backup still works

**Comment by lucahammer** [comment]
Logging out and in again worked for some people. The Twitter API became less reliable over the last few days.

Fedifinder fails after the first error from the API. Maybe someone can add some retries before it gives up or a button to try again if it fails.
