### ISSUE TITLE
Add unwanted domains

### ISSUE THREAD

**Issue by Wintiger0222** [lucahammer/fedifinder#231]
Here some list of false positive
* naver.com (Korean portal site/mail service)
* skeb.jp (Japanese Drawings Site)
* outlook.com (Mail Service)
* yahoo.co.* (portal site)
* hotmail.com (Mail Service)
* kakao.com (Korean mail service)
* hanmail.net (Korean mail service)
* hanmail2.net (Korean mail service)
* daum.net (Korean portal site/mail service)
* tistory.com (Korean blog/mail service)
* brunch.co.* (blog service)
* crepe.cm (Korean commision Site)

**Comment by lucahammer** [comment]
Thanks for the list.

Let me know if the domains are correctly ignored, so I can close the issue.
