### ISSUE TITLE
fedifinder.glitch.me Page is down

### ISSUE THREAD

**Issue by SarcevicAntonio** [lucahammer/fedifinder#242]
Sadly, the fedifinder page is currently down. 

It just says: "Oops! This project isn't running. If this is your project, check out the [Glitch Editor](https://glitch.com/edit/#!/fedifinder), or head over to the Help Center to [learn more](https://help.glitch.com/hc/en-us/articles/16287541477133-Project-Suspensions)."

Clicking on the editor brings another error "This project has been suspended Reason for suspension: Suspended for error while preparing project. If you think this was done in error, email support@glitch.com.".

**Comment by lucahammer** [comment]
I am working on it. Until then, you can use https://fedifinder-backup.glitch.me/

**Comment by lucahammer** [comment]
Fedifinder is up again. https://fedifinder.glitch.me/
