### ISSUE TITLE
Please pick up handles from display names

### ISSUE THREAD

**Issue by untitaker** [lucahammer/fedifinder#31]
I guess it isn't surprising given what cryptobros did with .eth "names".

Example users that link their mastodon handles in their name:

* https://twitter.com/NoraDotCodes
* https://twitter.com/obfuscurity

**Comment by untitaker** [comment]
Sorry, seems like you did already. obfuscurity was found, NoraDotCodes not

**Comment by lucahammer** [comment]
Thanks for the feedback. I put the account in my tester list and will report back.

**Comment by lucahammer** [comment]
I forgot what fixed it (regex or timeout), but it's fixed now.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/1390793/200048278-23734c85-41c4-4e34-a4bd-9d14312fd98f.png">

**Comment by untitaker** [comment]
thank you for this as well! By the way, what was the reason for filtering handles at all?

**Comment by lucahammer** [comment]
Mail addresses.
