### ISSUE TITLE
tech.lgbt is not recognized as valid fediverse instance

### ISSUE THREAD

**Issue by untitaker** [lucahammer/fedifinder#32]
it's excluded from exports via ETIMEDOUT. But the well-known data is there: https://tech.lgbt/.well-known/nodeinfo

**Comment by lucahammer** [comment]
Fixed by increasing the timeout to 10 seconds. 

<img width="527" alt="image" src="https://user-images.githubusercontent.com/1390793/200048568-d949740e-cddd-4a1c-8767-8494341222fb.png">

**Comment by untitaker** [comment]
thank you!
