### ISSUE TITLE
works, but does not find matches

### ISSUE THREAD

**Issue by alesti** [lucahammer/fedifinder#40]
Hi,
i used fedifinder some days ago and it worked fine, but today it answers with:

`Scanned 381 accounts and found 0 unique handles on domains that are part of the fedivers` 

I know two other which have the same issue right now.
Is that an issue on twitter-api side?
Can i create more (debug) output?

**Comment by lucahammer** [comment]
The tool isn't optimized at all, so the amount of people using it made it slow and it crashed way to often. I tried to fix it on the go, but coding on a touchscreen still needs some time.

The good news: It works again. And I set up two backups in case it becomes slow again.
fedifinder-backup.glitch.me and fedifinder-backup2.glitch.me.

Feel free to open another issue, if it fails again.
