### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by RobinMeis** [lucahammer/fedifinder#69]
For instances where LOCAL_DOMAIN != WEB_DOMAIN the mastodon documentation suggests to create a 302 redirect for /.well-known/webfinger.

Unfortunately fedifinder does not follow 302 redirects and displays the following error message for valid servers:
```
Maybe down, maybe not Fediverse. Error code: 302
```
fedifinder should follow redirects to handle those instances correctly.

**Comment by RobinMeis** [comment]
Maybe you also want to allow other redirect status codes as some instances seem to use 301.

**Comment by lucahammer** [comment]
I didn't want to close this. Sorry. 

Only following the redirect didn't help because I don't look for webfinger, but nodeinfo. Will have to thange that. See #61 .
