### ISSUE TITLE
Follow button has the wrong link for redirects

### ISSUE THREAD

**Issue by ixs** [lucahammer/fedifinder#86]
The follow button does not work for redirected instances as the URL is constructed incorrectly.

`client.js` builds the `authorize_interaction` URL in the `followButton()` function at https://github.com/lucahammer/fedifinder/blob/main/public/client.js#L248-L258.
That function is called in https://github.com/lucahammer/fedifinder/blob/main/public/client.js#L319 with the instance parameter set to the domain of the user_handle.

In case of a redirected domain, this is incorrect however.

The solution is probably to not use `user_handle.split("@")[2]` but instead use `domains[user_handle.split("@")[2]].local_domain` to fetch the right data.

**Comment by lucahammer** [comment]
Sorry for the misunderstanding. I thought you meant the follow in the other direction. 

At the moment the user domain isn't included with all domains. I will have to change that for your PR to work.
